# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TalentNextAssignment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
  pod 'GoogleSignIn'


  source 'https://github.com/CocoaPods/Specs.git'

  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  # Pods for TalentNextAssignment

end
